//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package optionality

import (
	"bytes"
	"embed"
	"encoding/json"
	jsonv2 "encoding/json/v2"
	"errors"
	"fmt"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __polytype_marshal(value any) ([]byte, error) {
	return jsonv2.Marshal(value, json.DefaultOptionsV1(), jsonv2.FormatNilSliceAsNull(false))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Config        *jsonschema.Schema
	__gen_jsonschema_compiled_NumericConfig *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("polytype: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("polytype: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("polytype: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Config
		__gen_jsonschema_compiled_Config = compile("Config", __zero.Schema())
	}

	{
		var __zero NumericConfig
		__gen_jsonschema_compiled_NumericConfig = compile("NumericConfig", __zero.Schema())
	}
}

func (Config) Schema() json.RawMessage {
	const fileName = "jsonschema/Config.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (NumericConfig) Schema() json.RawMessage {
	const fileName = "jsonschema/NumericConfig.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Config.
func (Config) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Config.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for NumericConfig.
func (NumericConfig) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_NumericConfig.Validate(inst)
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Config.
func (c Config) MarshalJSON() ([]byte, error) {
	type Alias Config
	type Wrapper struct {
		Alias
		Pet json.RawMessage `json:"pet,omitzero"`
	}
	wrapper := Wrapper{Alias: Alias(c)}
	var err error

	if c.Pet.Present {
		if wrapper.Pet, err = __jsonMarshal__optionality__Pet__b5e2b30ec0ee11c33157179140b477c8e97b5f1f0a98cf47a68561ae874663b1(c.Pet.Value); err != nil {
			return nil, fmt.Errorf("field pet: %w", err)
		}
	}

	return __polytype_marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Config.
func (c *Config) UnmarshalJSON(data []byte) (err error) {
	type Alias Config
	type Wrapper struct {
		Alias
		Pet json.RawMessage `json:"pet,omitzero"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Config(wrapper.Alias)

	if len(wrapper.Pet) > 0 {
		var __decoded0 Pet
		if __decoded0, err = __jsonUnmarshal__optionality__Pet__b5e2b30ec0ee11c33157179140b477c8e97b5f1f0a98cf47a68561ae874663b1(wrapper.Pet); err != nil {
			return err
		}
		__next.Pet.Value = __decoded0
		__next.Pet.Present = true
	}

	*c = __next
	return nil
}

func __jsonMarshal__optionality__Pet__b5e2b30ec0ee11c33157179140b477c8e97b5f1f0a98cf47a68561ae874663b1(value Pet) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Pet")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Cat:
		discriminator = "Cat"
		data, err = __polytype_marshal(&object)
	case Dog:
		discriminator = "Dog"
		data, err = __polytype_marshal(&object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Pet", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Pet: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"!kind",
		discriminator,
	)
}

func __jsonUnmarshal__optionality__Pet__b5e2b30ec0ee11c33157179140b477c8e97b5f1f0a98cf47a68561ae874663b1(data []byte) (Pet, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Cat":
		var obj Cat
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Dog":
		var obj Dog
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := __polytype_marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return __polytype_marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
