//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package basictypes

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (SimpleInt) Schema() json.RawMessage {
	const fileName = "jsonschema/SimpleInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SimpleString) Schema() json.RawMessage {
	const fileName = "jsonschema/SimpleString.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SimpleFloat) Schema() json.RawMessage {
	const fileName = "jsonschema/SimpleFloat.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SimpleStruct) Schema() json.RawMessage {
	const fileName = "jsonschema/SimpleStruct.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (TypeInNestedDecl) Schema() json.RawMessage {
	const fileName = "jsonschema/TypeInNestedDecl.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (AnotherNestedType) Schema() json.RawMessage {
	const fileName = "jsonschema/AnotherNestedType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
