// Package typescript projects the validated Go type grammar into TypeScript
// structural type declarations.
package typescript

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/constant"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/tylergannon/polytype/typegrammar"
)

// GeneratedHeader identifies files owned by this generator.
const GeneratedHeader = "// Code generated by polytype. DO NOT EDIT.\n"

type Options struct {
	Barrel bool
}

type File struct {
	Name    string
	Content []byte
}

// Generate validates defs and renders all declarations before returning any
// files. It never mutates defs.
func Generate(defs typegrammar.Definitions, options Options) ([]File, error) {
	if err := defs.Validate(); err != nil {
		return nil, fmt.Errorf("generate TypeScript: %w", err)
	}

	names := allocateNames(defs)
	aliases := make([]typeAlias, 0, len(defs))
	for _, def := range defs {
		expr, err := projector{names: names}.project(def.Type, def.Name.String())
		if err != nil {
			return nil, err
		}
		aliases = append(aliases, typeAlias{
			name:        names[def.Name],
			description: def.Description,
			typeExpr:    expr,
		})
	}

	files := []File{{Name: "types.ts", Content: printModule(aliases)}}
	if options.Barrel {
		exports := make([]string, 0, len(aliases))
		for _, alias := range aliases {
			exports = append(exports, alias.name)
		}
		sort.Strings(exports)
		files = append(files, File{Name: "index.ts", Content: printBarrel(exports)})
	}
	return files, nil
}

type projector struct {
	names map[typegrammar.Name]string
}

func (p projector) project(t typegrammar.Type, at string) (typeExpr, error) {
	switch n := t.(type) {
	case *typegrammar.Scalar:
		switch n.Kind {
		case typegrammar.Bool:
			return keywordType("boolean"), nil
		case typegrammar.String:
			return keywordType("string"), nil
		default:
			return keywordType("number"), nil
		}
	case *typegrammar.Time:
		return keywordType("string"), nil
	case *typegrammar.Enum:
		members := make([]typeExpr, 0, len(n.Members))
		for _, member := range n.Members {
			var literal string
			if n.Mode == typegrammar.EnumNames {
				literal = quote(member.Name)
			} else if n.Kind == typegrammar.String {
				literal = quote(constant.StringVal(member.Value))
			} else {
				var err error
				literal, err = numericLiteral(member.Value)
				if err != nil {
					return nil, fmt.Errorf("generate TypeScript: %s enum member %s: %w", at, member.Name, err)
				}
			}
			members = append(members, literalType(literal))
		}
		return union(members...), nil
	case *typegrammar.Object:
		if len(n.Fields) == 0 {
			// TypeScript's {} includes primitives. object is the strongest built-in
			// empty-object projection that excludes primitives and null without a
			// permissive any/unknown escape hatch.
			return keywordType("object"), nil
		}
		properties := make([]property, 0, len(n.Fields))
		for _, field := range n.Fields {
			typ, optional, err := p.projectField(field.Value, at+"."+field.GoName)
			if err != nil {
				return nil, err
			}
			properties = append(properties, property{
				name:        field.JSONName,
				description: field.Description,
				optional:    optional,
				typeExpr:    typ,
			})
		}
		return objectType{properties: properties}, nil
	case *typegrammar.Pointer:
		return p.project(n.Element, at+".pointer")
	case *typegrammar.Slice:
		element, err := p.project(n.Element, at+".items")
		if err != nil {
			return nil, err
		}
		return genericType{name: "Array", arguments: []typeExpr{element}}, nil
	case *typegrammar.Array:
		element, err := p.project(n.Element, at+".items")
		if err != nil {
			return nil, err
		}
		return genericType{name: "Array", arguments: []typeExpr{element}}, nil
	case *typegrammar.Ref:
		return referenceType(p.names[n.Target]), nil
	default:
		return nil, fmt.Errorf("generate TypeScript: %s: unsupported type constructor %T", at, t)
	}
}

func (p projector) projectField(value typegrammar.FieldValue, at string) (typeExpr, bool, error) {
	switch n := value.(type) {
	case *typegrammar.Required:
		typ, err := p.project(n.Type, at)
		return typ, false, err
	case *typegrammar.Optional:
		typ, err := p.project(n.Type, at)
		return typ, true, err
	case *typegrammar.Nullable:
		typ, err := p.project(n.Type, at)
		return union(typ, keywordType("null")), false, err
	case *typegrammar.Union:
		typ, err := p.projectUnion(*n, at)
		return typ, false, err
	case *typegrammar.OptionalUnion:
		typ, err := p.projectUnion(n.Union, at)
		return typ, true, err
	case *typegrammar.UnionSlice:
		typ, err := p.projectUnion(n.Union, at)
		if err != nil {
			return nil, false, err
		}
		return genericType{name: "Array", arguments: []typeExpr{typ}}, false, nil
	default:
		return nil, false, fmt.Errorf("generate TypeScript: %s: unsupported field constructor %T", at, value)
	}
}

func (p projector) projectUnion(u typegrammar.Union, at string) (typeExpr, error) {
	variants := make([]typeExpr, 0, len(u.Variants))
	for _, variant := range u.Variants {
		name, ok := p.names[variant.Implementation]
		if !ok {
			return nil, fmt.Errorf("generate TypeScript: %s: unresolved union implementation %s", at, variant.Implementation)
		}
		payload := genericType{
			name: "Omit",
			arguments: []typeExpr{
				referenceType(name),
				literalType(quote(u.Discriminator)),
			},
		}
		discriminator := objectType{properties: []property{{
			name:     u.Discriminator,
			typeExpr: literalType(quote(variant.Tag)),
		}}}
		variants = append(variants, intersection(payload, discriminator))
	}
	return union(variants...), nil
}

func numericLiteral(value constant.Value) (string, error) {
	_, exact := constant.Float64Val(constant.ToFloat(value))
	if !exact {
		return "", fmt.Errorf("integer %s is not exactly representable as a TypeScript number", value.ExactString())
	}
	return value.ExactString(), nil
}

func quote(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func allocateNames(defs typegrammar.Definitions) map[typegrammar.Name]string {
	bases := make(map[typegrammar.Name]string, len(defs))
	counts := make(map[string]int, len(defs))
	for _, def := range defs {
		base := safeIdentifier(def.Name.Name)
		if reservedWords[base] {
			base += "$type"
		}
		bases[def.Name] = base
		counts[base]++
	}

	names := make(map[typegrammar.Name]string, len(defs))
	for _, def := range defs {
		base := bases[def.Name]
		if counts[base] > 1 {
			identity := def.Name.PackagePath + "\x00" + def.Name.Name
			base += "$" + hex.EncodeToString([]byte(identity))
		}
		names[def.Name] = base
	}
	return names
}

func safeIdentifier(name string) string {
	var out strings.Builder
	for i, r := range name {
		if r == '_' || r < utf8.RuneSelf && (unicode.IsLetter(r) || i > 0 && unicode.IsDigit(r)) {
			out.WriteRune(r)
			continue
		}
		if r >= utf8.RuneSelf && (unicode.IsLetter(r) || i > 0 && unicode.IsDigit(r)) {
			fmt.Fprintf(&out, "_u%X_", r)
			continue
		}
		fmt.Fprintf(&out, "_u%X_", r)
	}
	return out.String()
}

var reservedWords = map[string]bool{
	"Array": true, "Omit": true,
	"any": true, "as": true, "asserts": true, "async": true, "await": true,
	"bigint": true, "boolean": true, "break": true, "case": true, "catch": true,
	"class": true, "const": true, "constructor": true, "continue": true, "debugger": true,
	"declare": true, "default": true, "delete": true, "do": true, "else": true,
	"enum": true, "export": true, "extends": true, "false": true, "finally": true,
	"for": true, "from": true, "function": true, "get": true, "global": true,
	"if": true, "implements": true, "import": true, "in": true, "infer": true,
	"instanceof": true, "interface": true, "is": true, "keyof": true, "let": true,
	"module": true, "namespace": true, "never": true, "new": true, "null": true,
	"number": true, "object": true, "of": true, "package": true, "private": true,
	"protected": true, "public": true, "readonly": true, "require": true, "return": true,
	"set": true, "static": true, "string": true, "super": true, "switch": true,
	"symbol": true, "this": true, "throw": true, "true": true, "try": true,
	"type": true, "typeof": true, "undefined": true, "unique": true, "unknown": true,
	"using": true, "var": true, "void": true, "while": true, "with": true, "yield": true,
}
