//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package interfaces_options

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (Owner) Schema() json.RawMessage {
	const fileName = "jsonschema/Owner.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Owner.
func (o Owner) MarshalJSON() ([]byte, error) {
	type Alias Owner
	type Wrapper struct {
		Alias
		IF json.RawMessage `json:"if"`
	}
	wrapper := Wrapper{Alias: Alias(o)}
	var err error

	if wrapper.IF, err = __jsonMarshal__interfaces_options__IFace__9dba3949824378de417a1c1fbf07c5150152ce951f178a8bedfad8311788dec0(o.IF); err != nil {
		return nil, fmt.Errorf("field if: %w", err)
	}

	return json.Marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Owner.
func (o *Owner) UnmarshalJSON(data []byte) (err error) {
	type Alias Owner
	type Wrapper struct {
		Alias
		IF json.RawMessage `json:"if"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Owner(wrapper.Alias)

	var __decoded0 IFace
	if __decoded0, err = __jsonUnmarshal__interfaces_options__IFace__9dba3949824378de417a1c1fbf07c5150152ce951f178a8bedfad8311788dec0(wrapper.IF); err != nil {
		return err
	}
	__next.IF = __decoded0

	*o = __next
	return nil
}

func __jsonMarshal__interfaces_options__IFace__9dba3949824378de417a1c1fbf07c5150152ce951f178a8bedfad8311788dec0(value IFace) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface IFace")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Impl1:
		discriminator = "Impl1"
		data, err = json.Marshal(&object)
	case Impl2:
		discriminator = "Impl2"
		data, err = json.Marshal(&object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for IFace", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for IFace: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"!kind",
		discriminator,
	)
}

func __jsonUnmarshal__interfaces_options__IFace__9dba3949824378de417a1c1fbf07c5150152ce951f178a8bedfad8311788dec0(data []byte) (IFace, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Impl1":
		var obj Impl1
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Impl2":
		var obj Impl2
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := json.Marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return json.Marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
