//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package model

import (
	"encoding/json"
	jsonv2 "encoding/json/v2"
	"errors"
	"fmt"
)

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __polytype_marshal(value any) ([]byte, error) {
	return jsonv2.Marshal(value, json.DefaultOptionsV1(), jsonv2.FormatNilSliceAsNull(false))
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Document.
func (d Document) MarshalJSON() ([]byte, error) {
	type Alias Document
	type Wrapper struct {
		Alias
		Content json.RawMessage `json:"content"`
	}
	wrapper := Wrapper{Alias: Alias(d)}
	var err error

	if d.Content == nil {
		return nil, fmt.Errorf("field content: nil registered interface slice")
	}
	__raw0 := make([]json.RawMessage, len(d.Content))
	for __index, __value := range d.Content {
		if __raw0[__index], err = __jsonMarshal__model__Block__41105f4b6461d9475a8b3eec550a6dfbee7291bc94a78159f5ce7edd537f6942(__value); err != nil {
			return nil, fmt.Errorf("field content[%d]: %w", __index, err)
		}
	}
	if wrapper.Content, err = __polytype_marshal(__raw0); err != nil {
		return nil, fmt.Errorf("field content: %w", err)
	}

	return __polytype_marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Document.
func (d *Document) UnmarshalJSON(data []byte) (err error) {
	type Alias Document
	type Wrapper struct {
		Alias
		Content json.RawMessage `json:"content"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Document(wrapper.Alias)

	if len(wrapper.Content) > 0 {
		var __raw0 []json.RawMessage
		if err = json.Unmarshal(wrapper.Content, &__raw0); err != nil {
			return fmt.Errorf("field content: %w", err)
		}
		var __decoded0 []Block
		if __raw0 != nil {
			__decoded0 = make([]Block, len(__raw0))
		}
		for __index, __raw := range __raw0 {
			if __decoded0[__index], err = __jsonUnmarshal__model__Block__41105f4b6461d9475a8b3eec550a6dfbee7291bc94a78159f5ce7edd537f6942(__raw); err != nil {
				return fmt.Errorf("field content[%d]: %w", __index, err)
			}
		}
		__next.Content = __decoded0
	}

	*d = __next
	return nil
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Section.
func (s Section) MarshalJSON() ([]byte, error) {
	type Alias Section
	type Wrapper struct {
		Alias
		Children json.RawMessage `json:"children"`
	}
	wrapper := Wrapper{Alias: Alias(s)}
	var err error

	if s.Children == nil {
		return nil, fmt.Errorf("field children: nil registered interface slice")
	}
	__raw0 := make([]json.RawMessage, len(s.Children))
	for __index, __value := range s.Children {
		if __raw0[__index], err = __jsonMarshal__model__Block__41105f4b6461d9475a8b3eec550a6dfbee7291bc94a78159f5ce7edd537f6942(__value); err != nil {
			return nil, fmt.Errorf("field children[%d]: %w", __index, err)
		}
	}
	if wrapper.Children, err = __polytype_marshal(__raw0); err != nil {
		return nil, fmt.Errorf("field children: %w", err)
	}

	return __polytype_marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Section.
func (s *Section) UnmarshalJSON(data []byte) (err error) {
	type Alias Section
	type Wrapper struct {
		Alias
		Children json.RawMessage `json:"children"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Section(wrapper.Alias)

	if len(wrapper.Children) > 0 {
		var __raw0 []json.RawMessage
		if err = json.Unmarshal(wrapper.Children, &__raw0); err != nil {
			return fmt.Errorf("field children: %w", err)
		}
		var __decoded0 []Block
		if __raw0 != nil {
			__decoded0 = make([]Block, len(__raw0))
		}
		for __index, __raw := range __raw0 {
			if __decoded0[__index], err = __jsonUnmarshal__model__Block__41105f4b6461d9475a8b3eec550a6dfbee7291bc94a78159f5ce7edd537f6942(__raw); err != nil {
				return fmt.Errorf("field children[%d]: %w", __index, err)
			}
		}
		__next.Children = __decoded0
	}

	*s = __next
	return nil
}

func __jsonMarshal__model__Block__41105f4b6461d9475a8b3eec550a6dfbee7291bc94a78159f5ce7edd537f6942(value Block) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Block")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Paragraph:
		discriminator = "Paragraph"
		data, err = __polytype_marshal(&object)
	case Section:
		discriminator = "Section"
		data, err = __polytype_marshal(&object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Block", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Block: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__model__Block__41105f4b6461d9475a8b3eec550a6dfbee7291bc94a78159f5ce7edd537f6942(data []byte) (Block, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "type")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Paragraph":
		var obj Paragraph
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Section":
		var obj Section
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := __polytype_marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return __polytype_marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
