//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.
package iota_global

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

// Each marked enum type is referenced here through its first typed constant
// so that its enum() marker is used from production code and keeps the shape
// the generator requires.
var (
	_ interface{ enum() } = PriorityLow
)

// MarshalJSON encodes Priority as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue Priority) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case PriorityLow:
		return []byte("0"), nil
	case PriorityMedium:
		return []byte("1"), nil
	case PriorityHigh:
		return []byte("2"), nil
	case PriorityUrgent:
		return []byte("3"), nil
	}
	return nil, fmt.Errorf("polytype: %v is not a declared member of enum Priority", int(__enumValue))
}

// UnmarshalJSON decodes Priority, accepting only the values of its
// declared constants.
func (__enumValue *Priority) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *int
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum Priority: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum Priority cannot be JSON null")
	}
	switch Priority(*__wire) {
	case PriorityLow:
	case PriorityMedium:
	case PriorityHigh:
	case PriorityUrgent:
	default:
		return fmt.Errorf("polytype: %v is not a declared member of enum Priority", *__wire)
	}
	*__enumValue = Priority(*__wire)
	return nil
}

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (Task) Schema() json.RawMessage {
	const fileName = "jsonschema/Task.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
