// Command record writes values.mjs: a generated list of named JavaScript value
// expressions covering the value shapes the type grammar admits. record.mjs
// maps each of them through the pinned devalue package to produce
// devalue/testdata/golden.json. See README.md.
package main

import (
	"fmt"
	"math/rand/v2"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"unicode/utf16"
)

// The generator is deterministic: rerunning it without editing it produces a
// byte-identical values.mjs, so a golden diff always means a real change.
const (
	seed      = 0x706f6c79 // "poly"
	nested    = 280        // randomly nested cases, on top of the curated ones
	maxDepth  = 3
	maxLength = 4
)

// primitives are the leaves. The strings deliberately include characters whose
// escaping, and whose UTF-16 code-unit ordering, differ from their UTF-8 byte
// ordering, because devalue's output is UTF-16 shaped.
var primitives = []string{
	"true", "false", "null",
	"0", "1", "-1", "3.5", "-0.25", "1e21", "1e-7",
	"9007199254740991",
	// Past 2^53, where the decided wire mapping is a lossy JavaScript number:
	// an int64 one above the safe range, and the largest uint64. Recording
	// them pins what devalue writes for the rounded double each becomes.
	"9007199254740993", "18446744073709551615",
	"1.7976931348623157e308", "5e-324",
	jsString(""), jsString("a"), jsString(`"`), jsString(`\`), jsString("\n"), jsString("\t"),
	jsString("\u0000"), jsString("\u0001"), jsString("\u2028"), jsString("\u2029"),
	jsString("雪"), jsString("😀"), jsString("￿"), jsString("</script>"),
	jsString("line1\nline2"),
}

// keys exercise property naming: escapes, non-ASCII, the integer-like keys
// JavaScript reorders ahead of string keys, and pairs whose relative order
// differs between UTF-8 bytes and UTF-16 code units.
var keys = []string{
	"", "a", "b", "type", "0", "10", "2",
	`key"quote`, `key\slash`, "key\nnewline",
	"\u0001", "\u2028", "雪", "😀", "￿", "__proto_x__", "constructor_",
}

var tags = []string{"created", "deleted", "", `wait"ing`, "雪"}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "record:", err)
		os.Exit(1)
	}
}

func run() error {
	random := rand.New(rand.NewPCG(seed, seed))
	var out strings.Builder
	out.WriteString("// Code generated by devalue/testdata/record. DO NOT EDIT.\n\nexport const values = [\n")

	write := func(name, expr string) {
		fmt.Fprintf(&out, "  [%s, %s],\n", jsString(name), expr)
	}
	for i, primitive := range primitives {
		write(fmt.Sprintf("primitive_%02d", i), primitive)
	}
	for i, expr := range []string{
		"[]", "[[]]", "[[], []]", "{}", `{"a": {}}`, "[{}]", `{"a": []}`,
		`{"0": 1, "a": 2, "10": 3, "2": 4}`,
		`{"雪": 1, "😀": 2, "￿": 3}`,
		`["shared", "shared", "shared"]`,
		`[{"type": "created", "name": "x"}, {"type": "deleted", "id": 1}]`,
	} {
		write(fmt.Sprintf("shape_%02d", i), expr)
	}
	write("shared_reference", `(() => { const value = {"x": 1}; return [value, value] })()`)
	write("self_cycle", `(() => { const value = {}; value.self = value; return value })()`)
	write("sparse_array", `Object.assign(Array(40), {39: "x"})`)
	write("special_undefined", `undefined`)
	write("special_nan", `NaN`)
	write("special_infinity", `Infinity`)
	write("special_negative_infinity", `-Infinity`)
	write("special_negative_zero", `-0`)
	write("special_bigint", `12345678901234567890n`)
	write("special_date", `new Date(1000000000000)`)
	write("special_regexp", `new RegExp("a+b", "gi")`)
	write("special_map", `new Map([["a", 1], ["b", 2]])`)
	write("special_set", `new Set([1, 2, 3])`)
	write("special_boxed", `Object(42)`)
	write("special_array_buffer", `new Uint8Array([1, 2, 3]).buffer`)
	write("special_null_proto", `Object.assign(Object.create(null), {"x": 1})`)

	// Repeated primitives: devalue hoists a repeated BigInt, or string of at
	// least 128 UTF-16 code units, when that makes the output shorter.
	write("repeated_string_127", `Array(3).fill("x".repeat(127))`)
	write("repeated_string_128", `Array(3).fill("x".repeat(128))`)
	write("repeated_string_astral", `Array(2).fill(`+jsString("\U0001F600")+`.repeat(64))`)
	write("repeated_string_multibyte_127", `Array(3).fill(`+jsString("\u96ea")+`.repeat(127))`)
	write("repeated_string_escaped", `Array(2).fill("<".repeat(128))`)
	write("repeated_string_ranked", `(() => { const s = "x".repeat(128); const o = {}; return [o, o, s, s, s] })()`)
	write("repeated_bigint_twice", `[12345678901234567890n, 12345678901234567890n]`)
	write("repeated_bigint_thrice", `Array(3).fill(12345678901234567890n)`)
	write("repeated_bigint_short_28", `Array(28).fill(1n)`)
	write("repeated_bigint_short_29", `Array(29).fill(1n)`)
	write("repeated_bigint_unnamed", `(() => { const o = {}; return [1n, 1n, 1n, o, o] })()`)
	write("repeated_map_key", `(() => { const s = "k".repeat(128); return new Map([[s, s]]) })()`)
	write("boxed_string_distinct", `(() => { const s = "x".repeat(128); return [Object(s), s, s] })()`)
	write("boxed_string_shared", `(() => { const s = "x".repeat(128); const b = Object(s); return [b, b, s, s] })()`)
	write("boxed_bigint_shared", `(() => { const b = Object(12345678901234567890n); return [b, b, 12345678901234567890n, 12345678901234567890n, 12345678901234567890n] })()`)

	// Sparse arrays: the Object.assign form starts from an allocator that
	// does not reserve every slot, and so does a hoisted sparse array once it
	// is long enough.
	write("sparse_array_96", `Object.assign(Array(96), {0: "x"})`)
	write("sparse_array_97", `Object.assign(Array(97), {0: "x"})`)
	write("sparse_array_1000", `Object.assign(Array(1000), {0: 1, 500: "x", 999: null})`)
	write("sparse_array_shared", `(() => { const a = Object.assign(Array(1000), {1: "x"}); return [a, a] })()`)
	write("sparse_array_cycle", `(() => { const a = Array(1000); a[500] = a; return a })()`)
	write("sparse_array_cycle_34", `(() => { const a = Array(34); a[0] = a; return a })()`)
	write("sparse_array_cycle_35", `(() => { const a = Array(35); a[0] = a; return a })()`)

	for i := range nested {
		write(fmt.Sprintf("nested_%03d", i), value(random, maxDepth))
	}

	out.WriteString("];\n")
	return os.WriteFile(filepath.Join(sourceDir(), "values.mjs"), []byte(out.String()), 0o644)
}

// value returns one JavaScript expression, nesting no deeper than depth.
func value(random *rand.Rand, depth int) string {
	if depth == 0 || random.IntN(100) < 40 {
		return primitives[random.IntN(len(primitives))]
	}
	switch random.IntN(3) {
	case 0:
		items := make([]string, random.IntN(maxLength+1))
		for i := range items {
			items[i] = value(random, depth-1)
		}
		return "[" + strings.Join(items, ", ") + "]"
	case 1:
		return object(random, depth, "")
	default:
		return object(random, depth, tags[random.IntN(len(tags))])
	}
}

// object returns a plain object literal. A non-empty tag produces the
// discriminated-union shape: a leading "type" property holding the tag.
func object(random *rand.Rand, depth int, tag string) string {
	used := map[string]bool{}
	var pairs []string
	if tag != "" {
		used["type"] = true
		pairs = append(pairs, `"type": `+jsString(tag))
	}
	for range random.IntN(maxLength + 1) {
		key := keys[random.IntN(len(keys))]
		if used[key] {
			continue
		}
		used[key] = true
		pairs = append(pairs, jsString(key)+": "+value(random, depth-1))
	}
	return "{" + strings.Join(pairs, ", ") + "}"
}

// jsString returns a JavaScript string literal escaping every code unit outside
// printable ASCII, so the generated file is pure ASCII and its bytes do not
// depend on how an editor normalizes Unicode.
func jsString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, unit := range utf16.Encode([]rune(s)) {
		switch {
		case unit == '"':
			b.WriteString(`\"`)
		case unit == '\\':
			b.WriteString(`\\`)
		case unit >= 0x20 && unit < 0x7f:
			b.WriteRune(rune(unit))
		default:
			fmt.Fprintf(&b, `\u%04x`, unit)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// sourceDir is this file's directory, so the output lands beside record.mjs no
// matter which directory `go run` was invoked from.
func sourceDir() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		panic("record: no source position")
	}
	return filepath.Dir(file)
}
