// Command record writes values.mjs: a generated list of named JavaScript value
// expressions covering the value shapes the type grammar admits. record.mjs
// maps each of them through the pinned devalue package to produce
// devalue/testdata/golden.json. See README.md.
package main

import (
	"fmt"
	"math/rand/v2"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"unicode/utf16"
)

// The generator is deterministic: rerunning it without editing it produces a
// byte-identical values.mjs, so a golden diff always means a real change.
const (
	seed      = 0x706f6c79 // "poly"
	nested    = 280        // randomly nested cases, on top of the curated ones
	maxDepth  = 3
	maxLength = 4
)

// primitives are the leaves. The strings deliberately include characters whose
// escaping, and whose UTF-16 code-unit ordering, differ from their UTF-8 byte
// ordering, because devalue's output is UTF-16 shaped.
var primitives = []string{
	"true", "false", "null",
	"0", "1", "-1", "3.5", "-0.25", "1e21", "1e-7",
	"9007199254740991",
	// Past 2^53, where the decided wire mapping is a lossy JavaScript number:
	// an int64 one above the safe range, and the largest uint64. Recording
	// them pins what devalue writes for the rounded double each becomes.
	"9007199254740993", "18446744073709551615",
	"1.7976931348623157e308", "5e-324",
	jsString(""), jsString("a"), jsString(`"`), jsString(`\`), jsString("\n"), jsString("\t"),
	jsString("\u0000"), jsString("\u0001"), jsString("\u2028"), jsString("\u2029"),
	jsString("雪"), jsString("😀"), jsString("￿"), jsString("</script>"),
	jsString("line1\nline2"),
}

// keys exercise property naming: escapes, non-ASCII, the integer-like keys
// JavaScript reorders ahead of string keys, and pairs whose relative order
// differs between UTF-8 bytes and UTF-16 code units.
var keys = []string{
	"", "a", "b", "type", "0", "10", "2",
	`key"quote`, `key\slash`, "key\nnewline",
	"\u0001", "\u2028", "雪", "😀", "￿", "__proto_x__", "constructor_",
}

var tags = []string{"created", "deleted", "", `wait"ing`, "雪"}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "record:", err)
		os.Exit(1)
	}
}

func run() error {
	random := rand.New(rand.NewPCG(seed, seed))
	var out strings.Builder
	out.WriteString("// Code generated by devalue/testdata/record. DO NOT EDIT.\n\nexport const values = [\n")

	write := func(name, expr string) {
		fmt.Fprintf(&out, "  [%s, %s],\n", jsString(name), expr)
	}
	for i, primitive := range primitives {
		write(fmt.Sprintf("primitive_%02d", i), primitive)
	}
	for i, expr := range []string{
		"[]", "[[]]", "[[], []]", "{}", `{"a": {}}`, "[{}]", `{"a": []}`,
		`{"0": 1, "a": 2, "10": 3, "2": 4}`,
		`{"雪": 1, "😀": 2, "￿": 3}`,
		`["shared", "shared", "shared"]`,
		`[{"type": "created", "name": "x"}, {"type": "deleted", "id": 1}]`,
	} {
		write(fmt.Sprintf("shape_%02d", i), expr)
	}
	for i := range nested {
		write(fmt.Sprintf("nested_%03d", i), value(random, maxDepth))
	}

	out.WriteString("];\n")
	return os.WriteFile(filepath.Join(sourceDir(), "values.mjs"), []byte(out.String()), 0o644)
}

// value returns one JavaScript expression, nesting no deeper than depth.
func value(random *rand.Rand, depth int) string {
	if depth == 0 || random.IntN(100) < 40 {
		return primitives[random.IntN(len(primitives))]
	}
	switch random.IntN(3) {
	case 0:
		items := make([]string, random.IntN(maxLength+1))
		for i := range items {
			items[i] = value(random, depth-1)
		}
		return "[" + strings.Join(items, ", ") + "]"
	case 1:
		return object(random, depth, "")
	default:
		return object(random, depth, tags[random.IntN(len(tags))])
	}
}

// object returns a plain object literal. A non-empty tag produces the
// discriminated-union shape: a leading "type" property holding the tag.
func object(random *rand.Rand, depth int, tag string) string {
	used := map[string]bool{}
	var pairs []string
	if tag != "" {
		used["type"] = true
		pairs = append(pairs, `"type": `+jsString(tag))
	}
	for range random.IntN(maxLength + 1) {
		key := keys[random.IntN(len(keys))]
		if used[key] {
			continue
		}
		used[key] = true
		pairs = append(pairs, jsString(key)+": "+value(random, depth-1))
	}
	return "{" + strings.Join(pairs, ", ") + "}"
}

// jsString returns a JavaScript string literal escaping every code unit outside
// printable ASCII, so the generated file is pure ASCII and its bytes do not
// depend on how an editor normalizes Unicode.
func jsString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, unit := range utf16.Encode([]rune(s)) {
		switch {
		case unit == '"':
			b.WriteString(`\"`)
		case unit == '\\':
			b.WriteString(`\\`)
		case unit >= 0x20 && unit < 0x7f:
			b.WriteRune(rune(unit))
		default:
			fmt.Fprintf(&b, `\u%04x`, unit)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// sourceDir is this file's directory, so the output lands beside record.mjs no
// matter which directory `go run` was invoked from.
func sourceDir() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		panic("record: no source position")
	}
	return filepath.Dir(file)
}
