//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package basictypes

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (IntType) Schema() json.RawMessage {
	const fileName = "jsonschema/IntType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (DefinedAsNamedType) Schema() json.RawMessage {
	const fileName = "jsonschema/DefinedAsNamedType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfPointerToInt) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfPointerToInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfPointerToNamedType) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfPointerToNamedType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfNamedType) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfNamedType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (NamedSliceType) Schema() json.RawMessage {
	const fileName = "jsonschema/NamedSliceType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (NamedNamedSliceType) Schema() json.RawMessage {
	const fileName = "jsonschema/NamedNamedSliceType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfNamedNamedSliceType) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfNamedNamedSliceType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (DefinedAsRemoteType) Schema() json.RawMessage {
	const fileName = "jsonschema/DefinedAsRemoteType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (DefinedAsRemoteSliceType) Schema() json.RawMessage {
	const fileName = "jsonschema/DefinedAsRemoteSliceType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (DefinedAsSliceOfRemoteSliceType) Schema() json.RawMessage {
	const fileName = "jsonschema/DefinedAsSliceOfRemoteSliceType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
