//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package enums

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

// Each marked enum type is referenced here through its first typed constant
// so that its enum() marker is used from production code and keeps the shape
// the generator requires.
var (
	_ interface{ enum() } = PriorityLow
	_ interface{ enum() } = StatusPending
)

// MarshalJSON encodes Priority as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue Priority) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case PriorityLow:
		return []byte("\"low\""), nil
	case PriorityMedium:
		return []byte("\"medium\""), nil
	case PriorityHigh:
		return []byte("\"high\""), nil
	}
	return nil, fmt.Errorf("polytype: %q is not a declared member of enum Priority", string(__enumValue))
}

// UnmarshalJSON decodes Priority, accepting only the values of its
// declared constants.
func (__enumValue *Priority) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *string
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum Priority: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum Priority cannot be JSON null")
	}
	switch Priority(*__wire) {
	case PriorityLow:
	case PriorityMedium:
	case PriorityHigh:
	default:
		return fmt.Errorf("polytype: %q is not a declared member of enum Priority", *__wire)
	}
	*__enumValue = Priority(*__wire)
	return nil
}

// MarshalJSON encodes Status as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue Status) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case StatusPending:
		return []byte("\"pending\""), nil
	case StatusInProgress:
		return []byte("\"in_progress\""), nil
	case StatusCompleted:
		return []byte("\"completed\""), nil
	case StatusFailed:
		return []byte("\"failed\""), nil
	}
	return nil, fmt.Errorf("polytype: %q is not a declared member of enum Status", string(__enumValue))
}

// UnmarshalJSON decodes Status, accepting only the values of its
// declared constants.
func (__enumValue *Status) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *string
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum Status: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum Status cannot be JSON null")
	}
	switch Status(*__wire) {
	case StatusPending:
	case StatusInProgress:
	case StatusCompleted:
	case StatusFailed:
	default:
		return fmt.Errorf("polytype: %q is not a declared member of enum Status", *__wire)
	}
	*__enumValue = Status(*__wire)
	return nil
}

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Status        *jsonschema.Schema
	__gen_jsonschema_compiled_Priority      *jsonschema.Schema
	__gen_jsonschema_compiled_Task          *jsonschema.Schema
	__gen_jsonschema_compiled_SliceOfStatus *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("polytype: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("polytype: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("polytype: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Status
		__gen_jsonschema_compiled_Status = compile("Status", __zero.Schema())
	}

	{
		var __zero Priority
		__gen_jsonschema_compiled_Priority = compile("Priority", __zero.Schema())
	}

	{
		var __zero Task
		__gen_jsonschema_compiled_Task = compile("Task", __zero.Schema())
	}

	{
		var __zero SliceOfStatus
		__gen_jsonschema_compiled_SliceOfStatus = compile("SliceOfStatus", __zero.Schema())
	}
}

func (Status) Schema() json.RawMessage {
	const fileName = "jsonschema/Status.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Priority) Schema() json.RawMessage {
	const fileName = "jsonschema/Priority.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Task) Schema() json.RawMessage {
	const fileName = "jsonschema/Task.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfStatus) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfStatus.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Status.
func (Status) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Status.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Priority.
func (Priority) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Priority.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Task.
func (Task) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Task.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for SliceOfStatus.
func (SliceOfStatus) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_SliceOfStatus.Validate(inst)
}
