//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package sealed_interface_slices

import (
	"embed"
	"encoding/json"
	jsonv2 "encoding/json/v2"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __polytype_marshal(value any) ([]byte, error) {
	return jsonv2.Marshal(value, json.DefaultOptionsV1(), jsonv2.FormatNilSliceAsNull(false))
}

func (Batch) Schema() json.RawMessage {
	const fileName = "jsonschema/Batch.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Batch.
func (b Batch) MarshalJSON() ([]byte, error) {
	type Alias Batch
	type Wrapper struct {
		Alias
		Events json.RawMessage `json:"events"`
	}
	wrapper := Wrapper{Alias: Alias(b)}
	var err error

	if b.Events == nil {
		return nil, fmt.Errorf("field events: nil registered interface slice")
	}
	__raw0 := make([]json.RawMessage, len(b.Events))
	for __index, __value := range b.Events {
		if __raw0[__index], err = __jsonMarshal__sealed_interface_slices__Event__80f7ceda90c597aaba537b676c5fe3ceac0533d4ae4d871a0455c7d08043a461(__value); err != nil {
			return nil, fmt.Errorf("field events[%d]: %w", __index, err)
		}
	}
	if wrapper.Events, err = __polytype_marshal(__raw0); err != nil {
		return nil, fmt.Errorf("field events: %w", err)
	}

	return __polytype_marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Batch.
func (b *Batch) UnmarshalJSON(data []byte) (err error) {
	type Alias Batch
	type Wrapper struct {
		Alias
		Events json.RawMessage `json:"events"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Batch(wrapper.Alias)

	if len(wrapper.Events) > 0 {
		var __raw0 []json.RawMessage
		if err = json.Unmarshal(wrapper.Events, &__raw0); err != nil {
			return fmt.Errorf("field events: %w", err)
		}
		var __decoded0 []Event
		if __raw0 != nil {
			__decoded0 = make([]Event, len(__raw0))
		}
		for __index, __raw := range __raw0 {
			if __decoded0[__index], err = __jsonUnmarshal__sealed_interface_slices__Event__80f7ceda90c597aaba537b676c5fe3ceac0533d4ae4d871a0455c7d08043a461(__raw); err != nil {
				return fmt.Errorf("field events[%d]: %w", __index, err)
			}
		}
		__next.Events = __decoded0
	}

	*b = __next
	return nil
}

func __jsonMarshal__sealed_interface_slices__Event__80f7ceda90c597aaba537b676c5fe3ceac0533d4ae4d871a0455c7d08043a461(value Event) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Event")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Created:
		discriminator = "Created"
		data, err = __polytype_marshal(&object)
	case *Deleted:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for Event", value)
		}
		discriminator = "Deleted"
		data, err = __polytype_marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Event", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Event: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"!kind",
		discriminator,
	)
}

func __jsonUnmarshal__sealed_interface_slices__Event__80f7ceda90c597aaba537b676c5fe3ceac0533d4ae4d871a0455c7d08043a461(data []byte) (Event, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Created":
		var obj Created
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Deleted":
		var obj Deleted
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := __polytype_marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return __polytype_marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
