package builder_test

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/tylergannon/polytype/internal/testutils"
)

type testCase struct {
	inputDir   string
	testName   string
	idempotent bool
}

// generatedArtifact reports whether a file under a fixture is one generation
// writes: a schema artifact in the jsonschema directory, or the generated Go
// file.
func generatedArtifact(rel string) bool {
	base := filepath.Base(rel)
	if base == "jsonschema_gen.go" || base == "polytype_gen.go" {
		return true
	}
	if filepath.Base(filepath.Dir(rel)) != "jsonschema" {
		return false
	}
	return strings.HasSuffix(base, ".json") || strings.HasSuffix(base, ".json.tmpl")
}

// assertGoldenArtifacts compares every generated artifact under dir with its
// golden, and fails on a golden with no generated counterpart or a generated
// artifact with no golden. A fixture cannot silently stop checking an output,
// and a stale golden cannot outlive the output it recorded.
func assertGoldenArtifacts(t *testing.T, dir string) {
	t.Helper()
	var goldens, artifacts []string
	require.NoError(t, filepath.WalkDir(dir, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		switch {
		case strings.HasSuffix(rel, ".golden"):
			goldens = append(goldens, rel)
		case generatedArtifact(rel):
			artifacts = append(artifacts, rel)
		}
		return nil
	}))
	require.NotEmpty(t, artifacts, "generation wrote no artifacts under %s", dir)
	for _, golden := range goldens {
		artifact := strings.TrimSuffix(golden, ".golden")
		require.Contains(t, artifacts, artifact, "golden %s has no generated artifact; delete the stale golden or fix generation", golden)
	}
	for _, artifact := range artifacts {
		require.Contains(t, goldens, artifact+".golden", "generated artifact %s has no golden; record one", artifact)
		testutils.AssertGoldenFile(t, filepath.Join(dir, artifact), ".golden")
	}
}

func TestBasic(t *testing.T) {
	t.Parallel()
	CmdSuccessAssertions := func(t *testing.T, stdout, stderr string, exitCode int) {
		require.Empty(t, stderr)
		require.Equal(t, 0, exitCode)
	}

	CodegenTest := func(tc testCase) {
		cwd, err := os.Getwd()
		require.NoError(t, err)
		tempDir := filepath.Join(cwd, "test_run", tc.testName)

		require.NoError(t, os.RemoveAll(tempDir))
		require.NoError(t, os.MkdirAll(tempDir, 0755))
		inputPathFull := filepath.Clean(filepath.Join(cwd, "..", tc.inputDir))
		fi, err := os.Stat(inputPathFull)
		require.NoError(t, err)
		require.True(t, fi.IsDir())
		require.NoError(t, testutils.CopyDir(inputPathFull, tempDir))

		// Ensure the temp module's dependencies are tidy before generation.
		preExit, preStdout, preStderr, err := testutils.RunCommand("go", tempDir, "mod", "tidy")
		require.NoError(t, err)
		// A clean module cache makes Go report dependency downloads on stderr.
		// That is normal progress output; the command's exit status determines success.
		require.Equal(t, 0, preExit, "stdout:\n%s\nstderr:\n%s", preStdout, preStderr)

		exitCode, stdout, stderr, err := testutils.RunCommand("go", tempDir, "generate", "./...")
		require.NoError(t, err)
		// Some Go versions emit a hint to run 'go mod tidy' on fresh copies; handle that gracefully.
		if exitCode == 0 && strings.Contains(stderr, "go: updates to go.mod needed") {
			_, _, _, _ = testutils.RunCommand("go", tempDir, "mod", "tidy")
			// Re-run generate to get clean stderr
			exitCode, stdout, stderr, err = testutils.RunCommand("go", tempDir, "generate", "./...")
			require.NoError(t, err)
		}
		CmdSuccessAssertions(t, stdout, stderr, exitCode)

		generatedPath := filepath.Join(tempDir, "jsonschema_gen.go")
		generated, err := os.ReadFile(generatedPath)
		require.NoError(t, err)
		require.True(t, strings.HasPrefix(string(generated), "//go:build !jsonschema\n\n"))
		require.Contains(t, string(generated), "// Code generated by polytype. DO NOT EDIT.\n\npackage ")
		require.NotContains(t, string(generated), "// +build")

		if tc.testName == "test1-basictypes" {
			docExit, docStdout, docStderr, docErr := testutils.RunCommand("go", tempDir, "doc", "-all", ".")
			require.NoError(t, docErr)
			require.Equal(t, 0, docExit, "stdout:\n%s\nstderr:\n%s", docStdout, docStderr)
			require.Contains(t, docStdout, "Package basictypes is the authored fixture documentation.")
			require.NotContains(t, docStdout, "Code generated by polytype")
		}

		assertGoldenArtifacts(t, tempDir)

		// Generated code may introduce new imports (e.g. jsonschema/v6); tidy before build.
		tidyExit, _, _, tidyErr := testutils.RunCommand("go", tempDir, "mod", "tidy")
		require.NoError(t, tidyErr)
		require.Equal(t, 0, tidyExit)

		if tc.idempotent {
			before := append([]byte(nil), generated...)
			exitCode, stdout, stderr, err = testutils.RunCommand("go", tempDir, "generate", "./...")
			require.NoError(t, err)
			CmdSuccessAssertions(t, stdout, stderr, exitCode)
			after, err := os.ReadFile(generatedPath)
			require.NoError(t, err)
			require.Equal(t, before, after, "second generation changed jsonschema_gen.go")
		}

		// Ensure generated code compiles in the temp module.
		buildExit, buildStdout, buildStderr, err := testutils.RunCommand("go", tempDir, "build", "./...")
		require.NoError(t, err)
		CmdSuccessAssertions(t, buildStdout, buildStderr, buildExit)

		// Fixture modules are nested modules, so their runtime tests must be run
		// explicitly after generation.
		testExit, _, testStderr, err := testutils.RunCommand("go", tempDir, "test", "./...")
		require.NoError(t, err)
		require.Empty(t, testStderr)
		require.Equal(t, 0, testExit)
	}

	cases := []testCase{
		{inputDir: "builder/testfixtures/basictypes", testName: "test1-basictypes"},
		{inputDir: "builder/testfixtures/indirecttypes", testName: "test2-indirecttypes"},
		{inputDir: "builder/testfixtures/enums", testName: "test3-enums"},
		{inputDir: "builder/testfixtures/structs", testName: "test4-structs"},
		{inputDir: "builder/testfixtures/interfaces", testName: "test5-interfaces"},
		{inputDir: "builder/testfixtures/providers", testName: "test6-providers"},
		{inputDir: "builder/testfixtures/entrypoints", testName: "test7-entrypoints"},
		{inputDir: "builder/testfixtures/providers_builder", testName: "test8-providers-builder"},
		{inputDir: "builder/testfixtures/v1_interfaces_options", testName: "test9-v1-interfaces-options"},
		{inputDir: "builder/testfixtures/v1_enums_stringmode", testName: "test10-v1-enums-stringmode", idempotent: true},
		{inputDir: "builder/testfixtures/traversal", testName: "test11-traversal"},
		{inputDir: "builder/testfixtures/optionality", testName: "test12-optionality"},
		{inputDir: "builder/testfixtures/union_codec", testName: "test13-union-codec", idempotent: true},
	}

	for _, tc := range cases {
		t.Run(tc.testName, func(t *testing.T) {
			t.Parallel()
			CodegenTest(tc)
		})
	}
}
