//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.
package test_options

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

// Each marked enum type is referenced here through its first typed constant
// so that its enum() marker is used from production code and keeps the shape
// the generator requires.
var (
	_ interface{ enum() } = ColorRed
	_ interface{ enum() } = LogDebug
	_ interface{ enum() } = PriorityLow
	_ interface{ enum() } = SeverityInfo
	_ interface{ enum() } = SizeSmall
	_ interface{ enum() } = StatusPending
	_ interface{ enum() } = Sunday
)

// MarshalJSON encodes Color as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue Color) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case ColorRed:
		return []byte("0"), nil
	case ColorGreen:
		return []byte("1"), nil
	case ColorBlue:
		return []byte("2"), nil
	case ColorYellow:
		return []byte("3"), nil
	case ColorPurple:
		return []byte("4"), nil
	}
	return nil, fmt.Errorf("polytype: %v is not a declared member of enum Color", int(__enumValue))
}

// UnmarshalJSON decodes Color, accepting only the values of its
// declared constants.
func (__enumValue *Color) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *int
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum Color: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum Color cannot be JSON null")
	}
	switch Color(*__wire) {
	case ColorRed:
	case ColorGreen:
	case ColorBlue:
	case ColorYellow:
	case ColorPurple:
	default:
		return fmt.Errorf("polytype: %v is not a declared member of enum Color", *__wire)
	}
	*__enumValue = Color(*__wire)
	return nil
}

// MarshalJSON encodes LogLevel as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue LogLevel) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case LogDebug:
		return []byte("0"), nil
	case LogInfo:
		return []byte("1"), nil
	case LogWarn:
		return []byte("2"), nil
	case LogError:
		return []byte("3"), nil
	case LogFatal:
		return []byte("4"), nil
	}
	return nil, fmt.Errorf("polytype: %v is not a declared member of enum LogLevel", int(__enumValue))
}

// UnmarshalJSON decodes LogLevel, accepting only the values of its
// declared constants.
func (__enumValue *LogLevel) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *int
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum LogLevel: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum LogLevel cannot be JSON null")
	}
	switch LogLevel(*__wire) {
	case LogDebug:
	case LogInfo:
	case LogWarn:
	case LogError:
	case LogFatal:
	default:
		return fmt.Errorf("polytype: %v is not a declared member of enum LogLevel", *__wire)
	}
	*__enumValue = LogLevel(*__wire)
	return nil
}

// MarshalJSON encodes Priority as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue Priority) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case PriorityLow:
		return []byte("\"low\""), nil
	case PriorityMedium:
		return []byte("\"medium\""), nil
	case PriorityHigh:
		return []byte("\"high\""), nil
	case PriorityUrgent:
		return []byte("\"urgent\""), nil
	}
	return nil, fmt.Errorf("polytype: %q is not a declared member of enum Priority", string(__enumValue))
}

// UnmarshalJSON decodes Priority, accepting only the values of its
// declared constants.
func (__enumValue *Priority) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *string
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum Priority: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum Priority cannot be JSON null")
	}
	switch Priority(*__wire) {
	case PriorityLow:
	case PriorityMedium:
	case PriorityHigh:
	case PriorityUrgent:
	default:
		return fmt.Errorf("polytype: %q is not a declared member of enum Priority", *__wire)
	}
	*__enumValue = Priority(*__wire)
	return nil
}

// MarshalJSON encodes Severity as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue Severity) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case SeverityInfo:
		return []byte("1"), nil
	case SeverityWarning:
		return []byte("2"), nil
	case SeverityError:
		return []byte("3"), nil
	case SeverityCritical:
		return []byte("4"), nil
	}
	return nil, fmt.Errorf("polytype: %v is not a declared member of enum Severity", int(__enumValue))
}

// UnmarshalJSON decodes Severity, accepting only the values of its
// declared constants.
func (__enumValue *Severity) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *int
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum Severity: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum Severity cannot be JSON null")
	}
	switch Severity(*__wire) {
	case SeverityInfo:
	case SeverityWarning:
	case SeverityError:
	case SeverityCritical:
	default:
		return fmt.Errorf("polytype: %v is not a declared member of enum Severity", *__wire)
	}
	*__enumValue = Severity(*__wire)
	return nil
}

// MarshalJSON encodes Size as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue Size) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case SizeSmall:
		return []byte("10"), nil
	case SizeMedium:
		return []byte("20"), nil
	case SizeLarge:
		return []byte("30"), nil
	case SizeXLarge:
		return []byte("40"), nil
	}
	return nil, fmt.Errorf("polytype: %v is not a declared member of enum Size", int(__enumValue))
}

// UnmarshalJSON decodes Size, accepting only the values of its
// declared constants.
func (__enumValue *Size) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *int
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum Size: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum Size cannot be JSON null")
	}
	switch Size(*__wire) {
	case SizeSmall:
	case SizeMedium:
	case SizeLarge:
	case SizeXLarge:
	default:
		return fmt.Errorf("polytype: %v is not a declared member of enum Size", *__wire)
	}
	*__enumValue = Size(*__wire)
	return nil
}

// MarshalJSON encodes Status as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue Status) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case StatusPending:
		return []byte("\"pending\""), nil
	case StatusActive:
		return []byte("\"active\""), nil
	case StatusComplete:
		return []byte("\"complete\""), nil
	case StatusCanceled:
		return []byte("\"canceled\""), nil
	}
	return nil, fmt.Errorf("polytype: %q is not a declared member of enum Status", string(__enumValue))
}

// UnmarshalJSON decodes Status, accepting only the values of its
// declared constants.
func (__enumValue *Status) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *string
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum Status: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum Status cannot be JSON null")
	}
	switch Status(*__wire) {
	case StatusPending:
	case StatusActive:
	case StatusComplete:
	case StatusCanceled:
	default:
		return fmt.Errorf("polytype: %q is not a declared member of enum Status", *__wire)
	}
	*__enumValue = Status(*__wire)
	return nil
}

// MarshalJSON encodes WeekDay as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue WeekDay) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case Sunday:
		return []byte("0"), nil
	case Monday:
		return []byte("1"), nil
	case Tuesday:
		return []byte("2"), nil
	case Wednesday:
		return []byte("3"), nil
	case Thursday:
		return []byte("4"), nil
	case Friday:
		return []byte("5"), nil
	case Saturday:
		return []byte("6"), nil
	}
	return nil, fmt.Errorf("polytype: %v is not a declared member of enum WeekDay", int(__enumValue))
}

// UnmarshalJSON decodes WeekDay, accepting only the values of its
// declared constants.
func (__enumValue *WeekDay) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *int
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum WeekDay: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum WeekDay cannot be JSON null")
	}
	switch WeekDay(*__wire) {
	case Sunday:
	case Monday:
	case Tuesday:
	case Wednesday:
	case Thursday:
	case Friday:
	case Saturday:
	default:
		return fmt.Errorf("polytype: %v is not a declared member of enum WeekDay", *__wire)
	}
	*__enumValue = WeekDay(*__wire)
	return nil
}

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (Product) Schema() json.RawMessage {
	const fileName = "jsonschema/Product.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Configuration) Schema() json.RawMessage {
	const fileName = "jsonschema/Configuration.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Person) Schema() json.RawMessage {
	const fileName = "jsonschema/Person.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Team) Schema() json.RawMessage {
	const fileName = "jsonschema/Team.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Task) Schema() json.RawMessage {
	const fileName = "jsonschema/Task.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (WorkItem) Schema() json.RawMessage {
	const fileName = "jsonschema/WorkItem.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
