//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package indirecttypes

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (SimpleInt) Schema() json.RawMessage {
	const fileName = "jsonschema/SimpleInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfInt) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfSimpleInt) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfSimpleInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfPointerToInt) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfPointerToInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfPointerToSimpleInt) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfPointerToSimpleInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (NamedSliceType) Schema() json.RawMessage {
	const fileName = "jsonschema/NamedSliceType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Person) Schema() json.RawMessage {
	const fileName = "jsonschema/Person.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfPerson) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfPerson.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (SliceOfPointerToPerson) Schema() json.RawMessage {
	const fileName = "jsonschema/SliceOfPointerToPerson.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (ComplexStruct) Schema() json.RawMessage {
	const fileName = "jsonschema/ComplexStruct.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func PointerToIntSchema(PointerToInt) json.RawMessage {
	const fileName = "jsonschema/PointerToInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
func PointerToSimpleIntSchema(PointerToSimpleInt) json.RawMessage {
	const fileName = "jsonschema/PointerToSimpleInt.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
func PointerToPersonSchema(PointerToPerson) json.RawMessage {
	const fileName = "jsonschema/PointerToPerson.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
