//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package structs

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Address      *jsonschema.Schema
	__gen_jsonschema_compiled_ContactInfo  *jsonschema.Schema
	__gen_jsonschema_compiled_RetryPolicy  *jsonschema.Schema
	__gen_jsonschema_compiled_Person       *jsonschema.Schema
	__gen_jsonschema_compiled_Organization *jsonschema.Schema
	__gen_jsonschema_compiled_Department   *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("polytype: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("polytype: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("polytype: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Address
		__gen_jsonschema_compiled_Address = compile("Address", __zero.Schema())
	}

	{
		var __zero ContactInfo
		__gen_jsonschema_compiled_ContactInfo = compile("ContactInfo", __zero.Schema())
	}

	{
		var __zero RetryPolicy
		__gen_jsonschema_compiled_RetryPolicy = compile("RetryPolicy", __zero.Schema())
	}

	{
		var __zero Person
		__gen_jsonschema_compiled_Person = compile("Person", __zero.Schema())
	}

	{
		var __zero Organization
		__gen_jsonschema_compiled_Organization = compile("Organization", __zero.Schema())
	}

	{
		var __zero Department
		__gen_jsonschema_compiled_Department = compile("Department", __zero.Schema())
	}
}

func (Address) Schema() json.RawMessage {
	const fileName = "jsonschema/Address.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (ContactInfo) Schema() json.RawMessage {
	const fileName = "jsonschema/ContactInfo.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (RetryPolicy) Schema() json.RawMessage {
	const fileName = "jsonschema/RetryPolicy.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Person) Schema() json.RawMessage {
	const fileName = "jsonschema/Person.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Organization) Schema() json.RawMessage {
	const fileName = "jsonschema/Organization.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Department) Schema() json.RawMessage {
	const fileName = "jsonschema/Department.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Address.
func (Address) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Address.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for ContactInfo.
func (ContactInfo) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_ContactInfo.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for RetryPolicy.
func (RetryPolicy) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_RetryPolicy.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Person.
func (Person) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Person.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Organization.
func (Organization) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Organization.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Department.
func (Department) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Department.Validate(inst)
}
