//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package uniontypes

import (
	"embed"
	"encoding/json"
	jsonv2 "encoding/json/v2"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __polytype_marshal(value any) ([]byte, error) {
	return jsonv2.Marshal(value, json.DefaultOptionsV1(), jsonv2.FormatNilSliceAsNull(false))
}

func (Circle) Schema() json.RawMessage {
	const fileName = "jsonschema/Circle.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Rectangle) Schema() json.RawMessage {
	const fileName = "jsonschema/Rectangle.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Triangle) Schema() json.RawMessage {
	const fileName = "jsonschema/Triangle.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (CreditCard) Schema() json.RawMessage {
	const fileName = "jsonschema/CreditCard.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (BankTransfer) Schema() json.RawMessage {
	const fileName = "jsonschema/BankTransfer.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (*DigitalWallet) Schema() json.RawMessage {
	const fileName = "jsonschema/DigitalWallet.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Drawing) Schema() json.RawMessage {
	const fileName = "jsonschema/Drawing.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Payment) Schema() json.RawMessage {
	const fileName = "jsonschema/Payment.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Drawing.
func (d Drawing) MarshalJSON() ([]byte, error) {
	type Alias Drawing
	type Wrapper struct {
		Alias
		Shapes json.RawMessage `json:"shapes"`
	}
	wrapper := Wrapper{Alias: Alias(d)}
	var err error

	if d.Shapes == nil {
		return nil, fmt.Errorf("field shapes: nil registered interface slice")
	}
	__raw0 := make([]json.RawMessage, len(d.Shapes))
	for __index, __value := range d.Shapes {
		if __raw0[__index], err = __jsonMarshal__uniontypes__Shape__47932c2de6ab4b045f3b027a0ed0585382b4cc8915a3b120f0ce46caa37aa6fd(__value); err != nil {
			return nil, fmt.Errorf("field shapes[%d]: %w", __index, err)
		}
	}
	if wrapper.Shapes, err = __polytype_marshal(__raw0); err != nil {
		return nil, fmt.Errorf("field shapes: %w", err)
	}

	return __polytype_marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Drawing.
func (d *Drawing) UnmarshalJSON(data []byte) (err error) {
	type Alias Drawing
	type Wrapper struct {
		Alias
		Shapes json.RawMessage `json:"shapes"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Drawing(wrapper.Alias)

	if len(wrapper.Shapes) > 0 {
		var __raw0 []json.RawMessage
		if err = json.Unmarshal(wrapper.Shapes, &__raw0); err != nil {
			return fmt.Errorf("field shapes: %w", err)
		}
		var __decoded0 []Shape
		if __raw0 != nil {
			__decoded0 = make([]Shape, len(__raw0))
		}
		for __index, __raw := range __raw0 {
			if __decoded0[__index], err = __jsonUnmarshal__uniontypes__Shape__47932c2de6ab4b045f3b027a0ed0585382b4cc8915a3b120f0ce46caa37aa6fd(__raw); err != nil {
				return fmt.Errorf("field shapes[%d]: %w", __index, err)
			}
		}
		__next.Shapes = __decoded0
	}

	*d = __next
	return nil
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Payment.
func (p Payment) MarshalJSON() ([]byte, error) {
	type Alias Payment
	type Wrapper struct {
		Alias
		Method json.RawMessage `json:"method"`
	}
	wrapper := Wrapper{Alias: Alias(p)}
	var err error

	if wrapper.Method, err = __jsonMarshal__uniontypes__PaymentMethod__3518dd514c46878508abbe640e74edf1421839b778e4ebbe556f02ece6e011e2(p.Method); err != nil {
		return nil, fmt.Errorf("field method: %w", err)
	}

	return __polytype_marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Payment.
func (p *Payment) UnmarshalJSON(data []byte) (err error) {
	type Alias Payment
	type Wrapper struct {
		Alias
		Method json.RawMessage `json:"method"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Payment(wrapper.Alias)

	var __decoded0 PaymentMethod
	if __decoded0, err = __jsonUnmarshal__uniontypes__PaymentMethod__3518dd514c46878508abbe640e74edf1421839b778e4ebbe556f02ece6e011e2(wrapper.Method); err != nil {
		return err
	}
	__next.Method = __decoded0

	*p = __next
	return nil
}

func __jsonMarshal__uniontypes__Shape__47932c2de6ab4b045f3b027a0ed0585382b4cc8915a3b120f0ce46caa37aa6fd(value Shape) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface Shape")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Circle:
		discriminator = "Circle"
		data, err = __polytype_marshal(&object)
	case Rectangle:
		discriminator = "Rectangle"
		data, err = __polytype_marshal(&object)
	case Triangle:
		discriminator = "Triangle"
		data, err = __polytype_marshal(&object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for Shape", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for Shape: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__uniontypes__Shape__47932c2de6ab4b045f3b027a0ed0585382b4cc8915a3b120f0ce46caa37aa6fd(data []byte) (Shape, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		return nil, errNoDiscriminator
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Circle":
		var obj Circle
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Rectangle":
		var obj Rectangle
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Triangle":
		var obj Triangle
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}
func __jsonMarshal__uniontypes__PaymentMethod__3518dd514c46878508abbe640e74edf1421839b778e4ebbe556f02ece6e011e2(value PaymentMethod) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface PaymentMethod")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case BankTransfer:
		discriminator = "BankTransfer"
		data, err = __polytype_marshal(&object)
	case CreditCard:
		discriminator = "CreditCard"
		data, err = __polytype_marshal(&object)
	case *DigitalWallet:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for PaymentMethod", value)
		}
		discriminator = "DigitalWallet"
		data, err = __polytype_marshal(object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for PaymentMethod", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for PaymentMethod: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__uniontypes__PaymentMethod__3518dd514c46878508abbe640e74edf1421839b778e4ebbe556f02ece6e011e2(data []byte) (PaymentMethod, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		return nil, errNoDiscriminator
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "BankTransfer":
		var obj BankTransfer
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "CreditCard":
		var obj CreditCard
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "DigitalWallet":
		var obj DigitalWallet
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := __polytype_marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return __polytype_marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
