package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/tylergannon/polytype/internal/testutils"
)

func TestGenJavaScriptFlags(t *testing.T) {
	t.Parallel()

	flags, options := newGenFlagSet(flag.ContinueOnError)
	require.NoError(t, flags.Parse([]string{"--javascript", "web/generated"}))
	require.Equal(t, "web/generated", options.javaScriptDir)

	flags, options = newGenFlagSet(flag.ContinueOnError)
	require.NoError(t, flags.Parse(nil))
	require.Empty(t, options.javaScriptDir)
}

// TestGenCommandJavaScriptOutputLifecycle drives the built CLI against a
// fresh consumer module outside the repository. It covers the JavaScript
// output lifecycle the outcome requires: a deterministic first generation, an
// idempotent rerun that touches nothing, switching between JavaScript and
// TypeScript modes in one directory, --no-changes detection of missing, stale,
// and obsolete files, and preservation of user-owned files.
func TestGenCommandJavaScriptOutputLifecycle(t *testing.T) {
	t.Parallel()

	repoRoot, err := filepath.Abs("..")
	require.NoError(t, err)

	root := t.TempDir()
	consumer := filepath.Join(root, "consumer")
	require.NoError(t, os.MkdirAll(consumer, 0o755))
	require.NoError(t, testutils.CopyDir("testdata/consumer", consumer))
	require.NoError(t, os.WriteFile(filepath.Join(consumer, "go.mod"), []byte(fmt.Sprintf(
		"module example.com/js-consumer\n\ngo %s\n\nrequire github.com/tylergannon/polytype v0.0.0\n\nreplace github.com/tylergannon/polytype => %s\n",
		goDirective(t, repoRoot), repoRoot)), 0o644))
	runGo(t, consumer, "mod", "tidy")

	generate := func(t *testing.T, args ...string) (int, string) {
		t.Helper()
		exit, stdout, stderr, err := testutils.RunCommand(cli, root, append([]string{"gen", "--target", consumer}, args...)...)
		require.NoError(t, err)
		return exit, stdout + stderr
	}

	generated := filepath.Join(consumer, "generated")

	// First generation: only types.js, carrying the ownership header.
	exit, output := generate(t, "--javascript", "consumer/generated")
	require.Equal(t, 0, exit, output)
	require.Equal(t, []string{"types.js"}, names(t, generated))
	require.Contains(t, string(read(t, filepath.Join(generated, "types.js"))),
		"// Code generated by polytype. DO NOT EDIT.")
	first := snapshot(t, generated)
	jsPath := filepath.Join(generated, "types.js")
	firstInfo, err := os.Stat(jsPath)
	require.NoError(t, err)

	// A second identical run writes nothing and leaves bytes and mtimes alone.
	exit, output = generate(t, "--javascript", generated)
	require.Equal(t, 0, exit, output)
	require.Equal(t, first, snapshot(t, generated))
	secondInfo, err := os.Stat(jsPath)
	require.NoError(t, err)
	require.Equal(t, firstInfo.ModTime(), secondInfo.ModTime(), "an unchanged types.js must not be rewritten")

	// Switch to TypeScript with a barrel in the same directory: types.js is
	// removed and types.ts plus index.ts are written.
	exit, output = generate(t, "--typescript", generated, "--typescript-barrel")
	require.Equal(t, 0, exit, output)
	require.Equal(t, []string{"index.ts", "types.ts"}, names(t, generated),
		"switching to TypeScript must remove the generated types.js and write types.ts and index.ts")
	require.Contains(t, string(read(t, filepath.Join(generated, "types.ts"))), "export type")
	require.Contains(t, string(read(t, filepath.Join(generated, "index.ts"))), "export type")

	// Switch back to JavaScript: both TypeScript files are removed.
	exit, output = generate(t, "--javascript", generated)
	require.Equal(t, 0, exit, output)
	require.Equal(t, []string{"types.js"}, names(t, generated),
		"switching to JavaScript must remove generated types.ts and index.ts")

	// --no-changes passes when the directory is up to date.
	exit, output = generate(t, "--javascript", generated, "--no-changes")
	require.Equal(t, 0, exit, output)
	require.Equal(t, []string{"types.js"}, names(t, generated))

	// A stale types.js fails --no-changes, names the path, and is left exactly
	// as it was.
	require.NoError(t, os.WriteFile(jsPath, append(read(t, jsPath), []byte("// deliberately stale\n")...), 0o644))
	stale := snapshot(t, generated)
	exit, output = generate(t, "--javascript", generated, "--no-changes")
	require.NotEqual(t, 0, exit, "a stale types.js must fail --no-changes")
	require.Contains(t, output, "types.js", "the drift message must name the changed JavaScript path")
	require.Equal(t, stale, snapshot(t, generated), "--no-changes must not rewrite the stale output")
	exit, output = generate(t, "--javascript", generated)
	require.Equal(t, 0, exit, output)
	require.Equal(t, first, snapshot(t, generated), "regeneration must restore the canonical bytes")

	// A generated TypeScript sibling is drift under JavaScript mode: it must
	// fail --no-changes and must not be removed by the check.
	require.NoError(t, os.WriteFile(filepath.Join(generated, "types.ts"),
		[]byte("// Code generated by polytype. DO NOT EDIT.\nexport type Stale = string;\n"), 0o644))
	withObsolete := snapshot(t, generated)
	exit, output = generate(t, "--javascript", generated, "--no-changes")
	require.NotEqual(t, 0, exit, "an obsolete generated types.ts must fail --no-changes")
	require.Contains(t, output, "types.ts", "the drift message must name the obsolete path")
	require.Equal(t, withObsolete, snapshot(t, generated), "--no-changes must not remove the obsolete file")
	// The next real run removes it.
	exit, output = generate(t, "--javascript", generated)
	require.Equal(t, 0, exit, output)
	require.Equal(t, first, snapshot(t, generated))

	// Plant headerless, user-owned files under every Polytype name plus an
	// unrelated sibling. None may be overwritten or removed.
	userFiles := map[string]string{
		"types.js":  "// application module\nexport const kept = true;\n",
		"types.ts":  "// application types\nexport type Kept = string;\n",
		"index.ts":  "// application barrel\nexport { kept } from \"./types.js\";\n",
		"notes.txt": "unrelated notes\n",
	}
	for name, content := range userFiles {
		require.NoError(t, os.WriteFile(filepath.Join(generated, name), []byte(content), 0o644))
	}
	exit, output = generate(t, "--no-changes")
	require.Equal(t, 0, exit, output, "--no-changes with JavaScript off must ignore the directory")
	for name, content := range userFiles {
		actual, readErr := os.ReadFile(filepath.Join(generated, name))
		require.NoError(t, readErr)
		require.Equal(t, content, string(actual), "%s must be preserved", name)
	}
	// Generating JavaScript into that directory must refuse to overwrite the
	// unowned types.js and leave every user file intact.
	exit, output = generate(t, "--javascript", generated)
	require.NotEqual(t, 0, exit, "an unowned types.js must be refused")
	require.Contains(t, output, "refusing to overwrite unowned JavaScript output")
	for name, content := range userFiles {
		actual, readErr := os.ReadFile(filepath.Join(generated, name))
		require.NoError(t, readErr)
		require.Equal(t, content, string(actual), "%s must be preserved after refusal", name)
	}
}

// TestGenCommandRejectsSameDirectoryDeclarationModes proves the CLI refuses a
// single directory claimed by both declaration modes while distinct
// directories remain fine.
func TestGenCommandRejectsSameDirectoryDeclarationModes(t *testing.T) {
	t.Parallel()

	repoRoot, err := filepath.Abs("..")
	require.NoError(t, err)

	root := t.TempDir()
	consumer := filepath.Join(root, "consumer")
	require.NoError(t, os.MkdirAll(consumer, 0o755))
	require.NoError(t, testutils.CopyDir("testdata/consumer", consumer))
	require.NoError(t, os.WriteFile(filepath.Join(consumer, "go.mod"), []byte(fmt.Sprintf(
		"module example.com/conflict-consumer\n\ngo %s\n\nrequire github.com/tylergannon/polytype v0.0.0\n\nreplace github.com/tylergannon/polytype => %s\n",
		goDirective(t, repoRoot), repoRoot)), 0o644))
	runGo(t, consumer, "mod", "tidy")

	generate := func(t *testing.T, args ...string) (int, string) {
		t.Helper()
		exit, stdout, stderr, err := testutils.RunCommand(cli, root, append([]string{"gen", "--target", consumer}, args...)...)
		require.NoError(t, err)
		return exit, stdout + stderr
	}

	exit, output := generate(t, "--typescript", "consumer/generated", "--javascript", "consumer/generated")
	require.NotEqual(t, 0, exit)
	require.Contains(t, output, "cannot target the same directory")
	_, statErr := os.Stat(filepath.Join(consumer, "generated"))
	require.ErrorIs(t, statErr, os.ErrNotExist, "a rejected conflict must write nothing")

	exit, output = generate(t, "--typescript", "consumer/ts", "--javascript", "consumer/js")
	require.Equal(t, 0, exit, output)
	require.Equal(t, []string{"types.ts"}, names(t, filepath.Join(consumer, "ts")))
	require.Equal(t, []string{"types.js"}, names(t, filepath.Join(consumer, "js")))
}
