//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package entrypoints

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (MethodType) Schema() json.RawMessage {
	const fileName = "jsonschema/MethodType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (FuncType) FuncTypeSchema() json.RawMessage {
	const fileName = "jsonschema/FuncType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (BuilderType) BuilderTypeSchema() json.RawMessage {
	const fileName = "jsonschema/BuilderType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func PointerFuncTypeSchema(PointerFuncType) json.RawMessage {
	const fileName = "jsonschema/PointerFuncType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
func InterfaceFuncTypeSchema(InterfaceFuncType) json.RawMessage {
	const fileName = "jsonschema/InterfaceFuncType.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
