//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package interfaces

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	yaml "go.yaml.in/yaml/v4"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

// Each marked enum type is referenced here through its first typed constant
// so that its enum() marker is used from production code and keeps the shape
// the generator requires.
var (
	_ interface{ enum() } = Val1
)

// MarshalJSON encodes MyEnumType as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue MyEnumType) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case Val1:
		return []byte("\"val1\""), nil
	case Val2:
		return []byte("\"val2\""), nil
	case Val3:
		return []byte("\"val3\""), nil
	case Val4:
		return []byte("\"val4\""), nil
	}
	return nil, fmt.Errorf("polytype: %q is not a declared member of enum MyEnumType", string(__enumValue))
}

// UnmarshalJSON decodes MyEnumType, accepting only the values of its
// declared constants.
func (__enumValue *MyEnumType) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *string
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum MyEnumType: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum MyEnumType cannot be JSON null")
	}
	switch MyEnumType(*__wire) {
	case Val1:
	case Val2:
	case Val3:
	case Val4:
	default:
		return fmt.Errorf("polytype: %q is not a declared member of enum MyEnumType", *__wire)
	}
	*__enumValue = MyEnumType(*__wire)
	return nil
}

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __gen_jsonschema_yamlNodeToJSON(node *yaml.Node) ([]byte, error) {
	var value any
	if err := node.Decode(&value); err != nil {
		return nil, err
	}
	return json.Marshal(value)
}

func (FancyStruct) Schema() json.RawMessage {
	const fileName = "jsonschema/FancyStruct.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// FancyStruct.
func (f FancyStruct) MarshalJSON() ([]byte, error) {
	type Alias FancyStruct
	type Wrapper struct {
		Alias
		IFace  json.RawMessage `json:"iface"`
		IFaces json.RawMessage `json:"ifaces"`
	}
	wrapper := Wrapper{Alias: Alias(f)}
	var err error

	if wrapper.IFace, err = __jsonMarshal__interfaces__TestInterface__b99650f5b4c7f2fe7b18a3b48f4a76abba1f4c6308b5160be95058ce4ca0acad(f.IFace); err != nil {
		return nil, fmt.Errorf("field iface: %w", err)
	}

	if f.IFaces == nil {
		return nil, fmt.Errorf("field ifaces: nil registered interface slice")
	}
	__raw1 := make([]json.RawMessage, len(f.IFaces))
	for __index, __value := range f.IFaces {
		if __raw1[__index], err = __jsonMarshal__interfaces__TestInterface__b99650f5b4c7f2fe7b18a3b48f4a76abba1f4c6308b5160be95058ce4ca0acad(__value); err != nil {
			return nil, fmt.Errorf("field ifaces[%d]: %w", __index, err)
		}
	}
	if wrapper.IFaces, err = json.Marshal(__raw1); err != nil {
		return nil, fmt.Errorf("field ifaces: %w", err)
	}

	return json.Marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// FancyStruct.
func (f *FancyStruct) UnmarshalJSON(data []byte) (err error) {
	type Alias FancyStruct
	type Wrapper struct {
		Alias
		IFace  json.RawMessage `json:"iface"`
		IFaces json.RawMessage `json:"ifaces"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := FancyStruct(wrapper.Alias)

	var __decoded0 TestInterface
	if __decoded0, err = __jsonUnmarshal__interfaces__TestInterface__b99650f5b4c7f2fe7b18a3b48f4a76abba1f4c6308b5160be95058ce4ca0acad(wrapper.IFace); err != nil {
		return err
	}
	__next.IFace = __decoded0

	if len(wrapper.IFaces) > 0 {
		var __raw1 []json.RawMessage
		if err = json.Unmarshal(wrapper.IFaces, &__raw1); err != nil {
			return fmt.Errorf("field ifaces: %w", err)
		}
		var __decoded1 []TestInterface
		if __raw1 != nil {
			__decoded1 = make([]TestInterface, len(__raw1))
		}
		for __index, __raw := range __raw1 {
			if __decoded1[__index], err = __jsonUnmarshal__interfaces__TestInterface__b99650f5b4c7f2fe7b18a3b48f4a76abba1f4c6308b5160be95058ce4ca0acad(__raw); err != nil {
				return fmt.Errorf("field ifaces[%d]: %w", __index, err)
			}
		}
		__next.IFaces = __decoded1
	}

	*f = __next
	return nil
}

// UnmarshalYAML translates YAML into the JSON data model before decoding
// FancyStruct with its JSON contract.
func (f *FancyStruct) UnmarshalYAML(node *yaml.Node) error {
	data, err := __gen_jsonschema_yamlNodeToJSON(node)
	if err != nil {
		return err
	}
	var next FancyStruct
	if err := json.Unmarshal(data, &next); err != nil {
		return err
	}
	*f = next
	return nil
}
func __jsonMarshal__interfaces__TestInterface__b99650f5b4c7f2fe7b18a3b48f4a76abba1f4c6308b5160be95058ce4ca0acad(value TestInterface) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface TestInterface")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case *PointerToTestInterface:
		if object == nil {
			return nil, fmt.Errorf("cannot marshal typed nil registered implementation %T for TestInterface", value)
		}
		discriminator = "PointerToTestInterface"
		data, err = json.Marshal(object)
	case TestInterface1:
		discriminator = "TestInterface1"
		data, err = json.Marshal(&object)
	case TestInterface2:
		discriminator = "TestInterface2"
		data, err = json.Marshal(&object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for TestInterface", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for TestInterface: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__interfaces__TestInterface__b99650f5b4c7f2fe7b18a3b48f4a76abba1f4c6308b5160be95058ce4ca0acad(data []byte) (TestInterface, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		return nil, errNoDiscriminator
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "PointerToTestInterface":
		var obj PointerToTestInterface
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return &obj, nil
	case "TestInterface1":
		var obj TestInterface1
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "TestInterface2":
		var obj TestInterface2
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := json.Marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return json.Marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
