//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package traversal

import (
	"embed"
	"encoding/json"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (TraversalHolder) Schema() json.RawMessage {
	const fileName = "jsonschema/TraversalHolder.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
