//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package enums_stringmode

import (
	"bytes"
	"embed"
	"encoding/json"
	jsonv2 "encoding/json/v2"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __polytype_marshal(value any) ([]byte, error) {
	return jsonv2.Marshal(value, json.DefaultOptionsV1(), jsonv2.FormatNilSliceAsNull(false))
}

func (Paint) Schema() json.RawMessage {
	const fileName = "jsonschema/Paint.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Paint.
func (p Paint) MarshalJSON() ([]byte, error) {
	type Alias Paint
	type Wrapper struct {
		Alias
		C json.RawMessage `json:"c"`
	}
	wrapper := Wrapper{Alias: Alias(p)}
	var err error

	if wrapper.C, err = __jsonMarshalEnum__Paint__C(p.C); err != nil {
		return nil, fmt.Errorf("field c: %w", err)
	}

	return __polytype_marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Paint.
func (p *Paint) UnmarshalJSON(data []byte) (err error) {
	type Alias Paint
	type Wrapper struct {
		Alias
		C json.RawMessage `json:"c"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Paint(wrapper.Alias)

	var __enumDecoded0 Color
	if __enumDecoded0, err = __jsonUnmarshalEnum__Paint__C(wrapper.C); err != nil {
		return fmt.Errorf("field c: %w", err)
	}
	__next.C = __enumDecoded0

	*p = __next
	return nil
}

func __jsonMarshalEnum__Paint__C(value Color) (json.RawMessage, error) {
	switch value {
	case ColorRed:
		return __polytype_marshal("ColorRed")
	case ColorGreen:
		return __polytype_marshal("ColorGreen")
	case ColorBlue:
		return __polytype_marshal("ColorBlue")
	default:
		return nil, errors.New("undeclared value for string-mode enum Color")
	}
}

func __jsonUnmarshalEnum__Paint__C(data []byte) (Color, error) {
	var zero Color
	if __jsonschema__isJSONNull(data) {
		return zero, errors.New("string-mode enum Color cannot be JSON null")
	}
	var wire string
	if err := json.Unmarshal(data, &wire); err != nil {
		return zero, fmt.Errorf("string-mode enum Color requires a JSON string: %w", err)
	}
	switch wire {
	case "ColorRed":
		return ColorRed, nil
	case "ColorGreen":
		return ColorGreen, nil
	case "ColorBlue":
		return ColorBlue, nil
	default:
		return zero, fmt.Errorf("unknown string-mode enum Color name %q", wire)
	}
}
func __jsonschema__isJSONNull(data []byte) bool {
	return bytes.Equal(bytes.TrimSpace(data), []byte("null"))
}
