//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package messages

import (
	"embed"
	"encoding/json"
	jsonv2 "encoding/json/v2"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __polytype_marshal(value any) ([]byte, error) {
	return jsonv2.Marshal(value, json.DefaultOptionsV1(), jsonv2.FormatNilSliceAsNull(false))
}

func (ToolFuncGetTypeInfo) Schema() json.RawMessage {
	const fileName = "jsonschema/ToolFuncGetTypeInfo.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (GeneratedTestResponse) Schema() json.RawMessage {
	const fileName = "jsonschema/GeneratedTestResponse.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Assertion.
func (a Assertion) MarshalJSON() ([]byte, error) {
	type Alias Assertion
	type Wrapper struct {
		Alias
		Value json.RawMessage `json:"value"`
	}
	wrapper := Wrapper{Alias: Alias(a)}
	var err error

	if wrapper.Value, err = __jsonMarshal__messages__AssertionValue__f72fdfb2f70c801e0971576b1607ca78647626b4b7cb89b213115af2322c2213(a.Value); err != nil {
		return nil, fmt.Errorf("field value: %w", err)
	}

	return __polytype_marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Assertion.
func (a *Assertion) UnmarshalJSON(data []byte) (err error) {
	type Alias Assertion
	type Wrapper struct {
		Alias
		Value json.RawMessage `json:"value"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Assertion(wrapper.Alias)

	var __decoded0 AssertionValue
	if __decoded0, err = __jsonUnmarshal__messages__AssertionValue__f72fdfb2f70c801e0971576b1607ca78647626b4b7cb89b213115af2322c2213(wrapper.Value); err != nil {
		return err
	}
	__next.Value = __decoded0

	*a = __next
	return nil
}

func __jsonMarshal__messages__AssertionValue__f72fdfb2f70c801e0971576b1607ca78647626b4b7cb89b213115af2322c2213(value AssertionValue) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface AssertionValue")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case AssertArrayLength:
		discriminator = "AssertArrayLength"
		data, err = __polytype_marshal(&object)
	case AssertBoolValue:
		discriminator = "AssertBoolValue"
		data, err = __polytype_marshal(&object)
	case AssertNumericValue:
		discriminator = "AssertNumericValue"
		data, err = __polytype_marshal(&object)
	case AssertStringValue:
		discriminator = "AssertStringValue"
		data, err = __polytype_marshal(&object)
	case AssertType:
		discriminator = "AssertType"
		data, err = __polytype_marshal(&object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for AssertionValue", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for AssertionValue: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"type",
		discriminator,
	)
}

func __jsonUnmarshal__messages__AssertionValue__f72fdfb2f70c801e0971576b1607ca78647626b4b7cb89b213115af2322c2213(data []byte) (AssertionValue, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["type"]; !ok {
		return nil, errNoDiscriminator
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "AssertArrayLength":
		var obj AssertArrayLength
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertBoolValue":
		var obj AssertBoolValue
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertNumericValue":
		var obj AssertNumericValue
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertStringValue":
		var obj AssertStringValue
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "AssertType":
		var obj AssertType
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := __polytype_marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return __polytype_marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
