//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package structs

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

// Each marked enum type is referenced here through its first typed constant
// so that its enum() marker is used from production code and keeps the shape
// the generator requires.
var (
	_ interface{ enum() } = Var1
)

// MarshalJSON encodes EnumType123 as its declared constant's own value.
// Any other value is rejected rather than written to the wire.
func (__enumValue EnumType123) MarshalJSON() ([]byte, error) {
	switch __enumValue {
	case Var1:
		return []byte("\"var1\""), nil
	case Var2:
		return []byte("\"var2\""), nil
	case Var3:
		return []byte("\"var3\""), nil
	case Var4:
		return []byte("\"var4\""), nil
	}
	return nil, fmt.Errorf("polytype: %q is not a declared member of enum EnumType123", string(__enumValue))
}

// UnmarshalJSON decodes EnumType123, accepting only the values of its
// declared constants.
func (__enumValue *EnumType123) UnmarshalJSON(data []byte) error {
	// The wire value is decoded through a pointer so that JSON null stays
	// distinguishable from the zero value of the underlying type: decoding
	// null into a bare value leaves it untouched, which would silently pass
	// the membership check whenever the zero value is a declared member.
	var __wire *string
	if err := json.Unmarshal(data, &__wire); err != nil {
		return fmt.Errorf("polytype: enum EnumType123: %w", err)
	}
	if __wire == nil {
		return errors.New("polytype: enum EnumType123 cannot be JSON null")
	}
	switch EnumType123(*__wire) {
	case Var1:
	case Var2:
	case Var3:
	case Var4:
	default:
		return fmt.Errorf("polytype: %q is not a declared member of enum EnumType123", *__wire)
	}
	*__enumValue = EnumType123(*__wire)
	return nil
}

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func (StructType1) Schema() json.RawMessage {
	const fileName = "jsonschema/StructType1.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (StructType2) Schema() json.RawMessage {
	const fileName = "jsonschema/StructType2.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (StructWithRefs) Schema() json.RawMessage {
	const fileName = "jsonschema/StructWithRefs.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (JSONTagNames) Schema() json.RawMessage {
	const fileName = "jsonschema/JSONTagNames.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}
