//go:build !jsonschema

// Code generated by polytype. DO NOT EDIT.

package v1_interfaces_options

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"

	yaml "go.yaml.in/yaml/v4"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed jsonschema
var __gen_jsonschema_fs embed.FS

var errNoDiscriminator = errors.New("no discriminator property 'type' found")

func __gen_jsonschema_panic(fname string, err error) {
	panic(fmt.Sprintf("error reading %s from embedded FS: %s", fname, err.Error()))
}

func __gen_jsonschema_yamlNodeToJSON(node *yaml.Node) ([]byte, error) {
	var value any
	if err := node.Decode(&value); err != nil {
		return nil, err
	}
	return json.Marshal(value)
}

func __gen_jsonschema_yamlToJSON(data []byte) ([]byte, error) {
	var value any
	if err := yaml.Load(data, &value, yaml.WithV4Defaults()); err != nil {
		return nil, err
	}
	return json.Marshal(value)
}

// Compiled JSON schemas for validation, initialized once at startup.
var (
	__gen_jsonschema_compiled_Plain *jsonschema.Schema
	__gen_jsonschema_compiled_Owner *jsonschema.Schema
)

func init() {
	compile := func(typeName string, schemaData json.RawMessage) *jsonschema.Schema {
		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaData))
		if err != nil {
			panic(fmt.Sprintf("polytype: failed to parse schema for %s: %s", typeName, err))
		}
		c := jsonschema.NewCompiler()
		url := typeName + ".json"
		if err := c.AddResource(url, doc); err != nil {
			panic(fmt.Sprintf("polytype: failed to add schema resource for %s: %s", typeName, err))
		}
		sch, err := c.Compile(url)
		if err != nil {
			panic(fmt.Sprintf("polytype: failed to compile schema for %s: %s", typeName, err))
		}
		return sch
	}

	{
		var __zero Plain
		__gen_jsonschema_compiled_Plain = compile("Plain", __zero.Schema())
	}

	{
		var __zero Owner
		__gen_jsonschema_compiled_Owner = compile("Owner", __zero.Schema())
	}
}

func (Plain) Schema() json.RawMessage {
	const fileName = "jsonschema/Plain.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

func (Owner) Schema() json.RawMessage {
	const fileName = "jsonschema/Owner.json"
	data, err := __gen_jsonschema_fs.ReadFile(fileName)
	if err != nil {
		__gen_jsonschema_panic(fileName, err)
	}
	return data
}

// ValidateJSON validates the given JSON bytes against the schema for Plain.
func (Plain) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Plain.Validate(inst)
}

// ValidateYAML validates YAML against the JSON Schema for Plain.
// YAML is interpreted using the schema's JSON property names.
func (Plain) ValidateYAML(data []byte) error {
	jsonData, err := __gen_jsonschema_yamlToJSON(data)
	if err != nil {
		return err
	}
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(jsonData))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Plain.Validate(inst)
}

// ValidateJSON validates the given JSON bytes against the schema for Owner.
func (Owner) ValidateJSON(data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Owner.Validate(inst)
}

// ValidateYAML validates YAML against the JSON Schema for Owner.
// YAML is interpreted using the schema's JSON property names.
func (Owner) ValidateYAML(data []byte) error {
	jsonData, err := __gen_jsonschema_yamlToJSON(data)
	if err != nil {
		return err
	}
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(jsonData))
	if err != nil {
		return err
	}
	return __gen_jsonschema_compiled_Owner.Validate(inst)
}

// MarshalJSON is a generated custom json.Marshaler implementation for
// Owner.
func (o Owner) MarshalJSON() ([]byte, error) {
	type Alias Owner
	type Wrapper struct {
		Alias
		IF         json.RawMessage `json:"if" yaml:"yaml_if"`
		IFaces     json.RawMessage `json:"ifs" yaml:"yaml_ifs"`
		OptionalIF json.RawMessage `json:"optional_if,omitzero" yaml:"yaml_optional"`
	}
	wrapper := Wrapper{Alias: Alias(o)}
	var err error

	if wrapper.IF, err = __jsonMarshal__v1_interfaces_options__IFace__6af605dbb1d39d3a8bf61c632fa0f85e2b2d752230aeb3822843f2fa9b62d5b5(o.IF); err != nil {
		return nil, fmt.Errorf("field if: %w", err)
	}

	if o.IFaces == nil {
		return nil, fmt.Errorf("field ifs: nil registered interface slice")
	}
	__raw1 := make([]json.RawMessage, len(o.IFaces))
	for __index, __value := range o.IFaces {
		if __raw1[__index], err = __jsonMarshal__v1_interfaces_options__IFace__6af605dbb1d39d3a8bf61c632fa0f85e2b2d752230aeb3822843f2fa9b62d5b5(__value); err != nil {
			return nil, fmt.Errorf("field ifs[%d]: %w", __index, err)
		}
	}
	if wrapper.IFaces, err = json.Marshal(__raw1); err != nil {
		return nil, fmt.Errorf("field ifs: %w", err)
	}

	if o.OptionalIF.Present {
		if wrapper.OptionalIF, err = __jsonMarshal__v1_interfaces_options__IFace__6af605dbb1d39d3a8bf61c632fa0f85e2b2d752230aeb3822843f2fa9b62d5b5(o.OptionalIF.Value); err != nil {
			return nil, fmt.Errorf("field optional_if: %w", err)
		}
	}

	return json.Marshal(&wrapper)
}

// UnmarshalJSON is a generated custom json.Unmarshaler implementation for
// Owner.
func (o *Owner) UnmarshalJSON(data []byte) (err error) {
	type Alias Owner
	type Wrapper struct {
		Alias
		IF         json.RawMessage `json:"if" yaml:"yaml_if"`
		IFaces     json.RawMessage `json:"ifs" yaml:"yaml_ifs"`
		OptionalIF json.RawMessage `json:"optional_if,omitzero" yaml:"yaml_optional"`
	}
	var wrapper Wrapper
	if err = json.Unmarshal(data, &wrapper); err != nil {
		return err
	}
	__next := Owner(wrapper.Alias)

	var __decoded0 IFace
	if __decoded0, err = __jsonUnmarshal__v1_interfaces_options__IFace__6af605dbb1d39d3a8bf61c632fa0f85e2b2d752230aeb3822843f2fa9b62d5b5(wrapper.IF); err != nil {
		return err
	}
	__next.IF = __decoded0

	if len(wrapper.IFaces) > 0 {
		var __raw1 []json.RawMessage
		if err = json.Unmarshal(wrapper.IFaces, &__raw1); err != nil {
			return fmt.Errorf("field ifs: %w", err)
		}
		var __decoded1 []IFace
		if __raw1 != nil {
			__decoded1 = make([]IFace, len(__raw1))
		}
		for __index, __raw := range __raw1 {
			if __decoded1[__index], err = __jsonUnmarshal__v1_interfaces_options__IFace__6af605dbb1d39d3a8bf61c632fa0f85e2b2d752230aeb3822843f2fa9b62d5b5(__raw); err != nil {
				return fmt.Errorf("field ifs[%d]: %w", __index, err)
			}
		}
		__next.IFaces = __decoded1
	}

	if len(wrapper.OptionalIF) > 0 {
		var __decoded2 IFace
		if __decoded2, err = __jsonUnmarshal__v1_interfaces_options__IFace__6af605dbb1d39d3a8bf61c632fa0f85e2b2d752230aeb3822843f2fa9b62d5b5(wrapper.OptionalIF); err != nil {
			return err
		}
		__next.OptionalIF.Value = __decoded2
		__next.OptionalIF.Present = true
	}

	*o = __next
	return nil
}

// UnmarshalYAML translates YAML into the JSON data model before decoding
// Owner with its JSON contract.
func (o *Owner) UnmarshalYAML(node *yaml.Node) error {
	data, err := __gen_jsonschema_yamlNodeToJSON(node)
	if err != nil {
		return err
	}
	var next Owner
	if err := json.Unmarshal(data, &next); err != nil {
		return err
	}
	*o = next
	return nil
}

// UnmarshalYAML translates YAML into the JSON data model before decoding
// Plain with its JSON contract.
func (p *Plain) UnmarshalYAML(node *yaml.Node) error {
	data, err := __gen_jsonschema_yamlNodeToJSON(node)
	if err != nil {
		return err
	}
	var next Plain
	if err := json.Unmarshal(data, &next); err != nil {
		return err
	}
	*p = next
	return nil
}
func __jsonMarshal__v1_interfaces_options__IFace__6af605dbb1d39d3a8bf61c632fa0f85e2b2d752230aeb3822843f2fa9b62d5b5(value IFace) (json.RawMessage, error) {
	if value == nil {
		return nil, fmt.Errorf("cannot marshal nil registered interface IFace")
	}
	var (
		data          []byte
		err           error
		discriminator string
	)
	switch object := value.(type) {
	case Impl1:
		discriminator = "Impl1"
		data, err = json.Marshal(&object)
	case Impl2:
		discriminator = "Impl2"
		data, err = json.Marshal(&object)
	default:
		return nil, fmt.Errorf("unregistered dynamic implementation %T for IFace", value)
	}
	if err != nil {
		return nil, fmt.Errorf("marshal registered implementation %T for IFace: %w", value, err)
	}
	return __jsonschema__marshalUnionObject(data,
		"!kind",
		discriminator,
	)
}

func __jsonUnmarshal__v1_interfaces_options__IFace__6af605dbb1d39d3a8bf61c632fa0f85e2b2d752230aeb3822843f2fa9b62d5b5(data []byte) (IFace, error) {
	var (
		temp          map[string]json.RawMessage
		discriminator string
		err           = json.Unmarshal(data, &temp)
	)

	if err != nil {
		return nil, err
	} else if _tempDiscriminator, ok := temp["!kind"]; !ok {
		// per-field discriminator property
		return nil, fmt.Errorf("no discriminator property '%s' found", "!kind")
	} else if discriminator, err = __jsonschema__decodeDiscriminator(_tempDiscriminator); err != nil {
		return nil, __jsonschema__unmarshalDiscriminatorError(_tempDiscriminator, err)
	}
	switch discriminator {
	case "Impl1":
		var obj Impl1
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	case "Impl2":
		var obj Impl2
		if err = json.Unmarshal(data, &obj); err != nil {
			return nil, err
		}
		return obj, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", discriminator)
	}
}

func __jsonschema__marshalUnionObject(data []byte, discriminatorProp, discriminatorValue string) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object: %w", err)
	}
	if object == nil {
		return nil, fmt.Errorf("registered union payload must encode as a JSON object, got null")
	}
	if encoded, ok := object[discriminatorProp]; ok {
		current, err := __jsonschema__decodeDiscriminator(encoded)
		if err != nil {
			return nil, fmt.Errorf("discriminator property %q must be a string: %w", discriminatorProp, err)
		}
		if current != discriminatorValue {
			return nil, fmt.Errorf("discriminator property %q is %q, want registered value %q", discriminatorProp, current, discriminatorValue)
		}
	} else {
		encoded, err := json.Marshal(discriminatorValue)
		if err != nil {
			return nil, err
		}
		object[discriminatorProp] = encoded
	}
	return json.Marshal(object)
}

func __jsonschema__decodeDiscriminator(discriminator json.RawMessage) (string, error) {
	var value *string
	if err := json.Unmarshal(discriminator, &value); err != nil {
		return "", err
	}
	if value == nil {
		return "", errors.New("JSON null is not a string")
	}
	return *value, nil
}

func __jsonschema__unmarshalDiscriminatorError(discriminator json.RawMessage, err error) error {
	return fmt.Errorf("unable to unmarshal discriminator value %v: %w", discriminator, err)
}
